### PR TITLE
add percentile999 in statistics

### PR DESCRIPTION
**Pull request by fredchenbj**
add a `percentile999` field in `HistogramData` of rocksdb statistics. 

Signed-off-by: fredchenbj <cfworking@163.com>

### CODE REVIEW

**Comment by Connor1996** [comment]
better to merge it in upstream(facebook repo) first

**Comment by fredchenbj** [comment]
> better to merge it in upstream(facebook repo) first

OK.

**Comment by fredchenbj** [comment]
have it in upstream: https://github.com/facebook/rocksdb/pull/6201

**Comment by yiwu-arbug** [comment]
Closing old PRs with no progress.

**Pull request closed without merging**
