### PR TITLE
Support dynamically changing `max_subcompactions` via `SetOptions()` …

### PR DESCRIPTION
**Pull request by ethercflow**
…(#262)

Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>

### CODE REVIEW

**Comment by ethercflow** [comment]
Although there is already a similar PR at upstream https://github.com/facebook/rocksdb/commit/b0c5ecd6b33398eae73c5d22b37fa820f41c804e,
but I found some differences in the base code. After consulting with Bokang, we decided to re-enable this PR.

@Connor1996 @yiwu-arbug PTAL

**Comment by glorv** [comment]
Shall we also port the unit tests in https://github.com/facebook/rocksdb/pull/7159 into this PR?

**Comment by glorv** [comment]
@Connor1996 @tabokie  PTAL, thanks~

**Review by Connor1996 — COMMENTED** [review]
Please add a test case to cover it

**Comment by Connor1996** [comment]
> Shall we also port the unit tests in [facebook#7159](https://github.com/facebook/rocksdb/pull/7159) into this PR?

Yes

**Comment by ethercflow** [comment]
There's a new [PR](https://github.com/tikv/rocksdb/pull/310) to fix this, so close this.

**Pull request closed without merging**
