### PR TITLE
offload periodic work

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]
Can you describe the purpose and also send the patch to upstream?

**Review by Connor1996 — COMMENTED** [review]
What's it for?

**Comment by tabokie** [comment]
> What's it for?

It's a waste to schedule work for each instance because the statistics and logger is shared.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
