### PR TITLE
cherry-pick compaction enhancements

### PR DESCRIPTION
**Pull request by tabokie**
- https://github.com/facebook/rocksdb/pull/9570
- https://github.com/facebook/rocksdb/pull/9311
- https://github.com/facebook/rocksdb/pull/9725
- https://github.com/facebook/rocksdb/pull/10057
- https://github.com/facebook/rocksdb/pull/10070
- https://github.com/facebook/rocksdb/pull/10317
- https://github.com/facebook/rocksdb/pull/10518
- https://github.com/facebook/rocksdb/pull/11165
- https://github.com/facebook/rocksdb/pull/11321
- https://github.com/facebook/rocksdb/pull/11340
- https://github.com/facebook/rocksdb/pull/11375
- https://github.com/facebook/rocksdb/pull/11468

Unfortunately https://github.com/facebook/rocksdb/pull/10655 is not included because it depends on a big refactor earlier.

Retiring our own changes:
- https://github.com/tikv/rocksdb/pull/218

Signed-off-by: tabokie <xy.tao@outlook.com>

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by tonyxuqqi** [comment]
Can rocksdb's UT pass with this change @tabokie

**Comment by tabokie** [comment]
> Can rocksdb's UT pass with this change @tabokie

All tests are run in CI and they have passed.

**Comment by tabokie** [comment]
Superseded by https://github.com/tikv/rocksdb/pull/346

**Pull request closed without merging**
