### PR TITLE
fix key boundaries in compaction filter context

### LINKED ISSUE #317: I think start is userkey here!
https://github.com/tikv/rocksdb/blob/ce0ea61aecd53ac02a0e7da2b166961c7d98650a/db/compaction/compaction.cc#L549

ExtractUserKey(*start) will assert false!

same to ExtractUserKey(*end)

Am I right?

### PR DESCRIPTION
**Pull request by zgcbj**
Fix #317

### CODE REVIEW

**Review by tabokie — COMMENTED** [review]
DCO and Format is failing.

**Review by tabokie — APPROVED** [review]

**Review by Connor1996 — COMMENTED** [review]
Please add a test to cover it

**Comment by zgcbj** [comment]
I want test these code use subcompaction with compactionfilterfactory, but it failed at generate data. I can`t fix it. Please help me figure it out.

**Pull request closed without merging**
