### PR TITLE
disable ignore_unknown_options only for lower version

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

Only enable force option check when reading options file from lower version.

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
LGTM. Though we still can't downgrade to lower version for previous version

**Comment by tabokie** [comment]
> LGTM. Though we still can't downgrade to lower version for previous version

It seem unsolvable for older releases, we can only make sure 5.2 can rollback to upcoming minor versions of 5.0 and 5.1, and then rollback to older releases because Options file will be updated without unrecognized items.

I'll also revert the disable-write-stall config for 5.0 and 5.1 later.

**Comment by yiwu-arbug** [comment]
Shall we ignore unknown options only when current version is no less than the previous version, same as what #258 did?

**Review by yiwu-arbug — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
