### PR TITLE
add HighPriCache and LowPriCache interface to implement PrioritizedCache

### PR DESCRIPTION
**Pull request by haoxiang47**
From this issue: https://github.com/tikv/titan/issues/127
add two interface: NewHighPriCache and NewLowPriCache to implement PrioritizedCache

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@haoxiang47 Thanks for update! Comments:
1. With `PrioritizedCache`, what we want to achieve is having a single `LRUCache` as backend, but expose two wrapper for it. When using the `HighPriCache` wrapper, on insert cache item, always override priority to high; vice-versa for `LowPriCache`. It doesn't not change underlying `high-pri-pool-ratio`.
2. Can you move the change to titan repo (github.com/tikv/titan)? We would like to keep rocksdb change at minimum.

**Comment by haoxiang47** [comment]
ok, I will update my code:
1. from the lru_cache.cc, I find that only in `high_pri_pool_ratio_ > 0 && (e->IsHighPri() || e->HasHit()` the element can insert to the high priority, so if we do not change the `high_pri_pool_ratio_`, maybe we can not always insert into the high lru list? or we just want to add a wrapper that all element from this wapper will be overwrite the priority, but do not change the cache origin logic?
2. yes I will move it to the titan

**Comment by yiwu-arbug** [comment]
> or we just want to add a wrapper that all element from this wapper will be overwrite the priority, but do not change the cache origin logic?

This is what I want to do.

**Comment by yiwu-arbug** [comment]
Closing in favor of https://github.com/tikv/titan/pull/142

**Pull request closed without merging**
