### PR TITLE
Defer live file query in FindObsoleteFiles

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

This PR contains two optimizations to reduce DB mutex held time when generating obsolete files purging jobs:
1. Avoid querying live files when there is no obsolete files to purge

This relies on the fact that `PurgeObsoleteFiles()` is only called when `JobContext::HaveSomethingToDelete()` is true, and the job context is unchanged after calling `FindObsoleteFiles()`

2. Query live files outside of DB mutex

This relies on the fact that `Version` will only be public when it's finalized, and finalized version has immutable file list.

We examine the patch in an artificial workload, where iterators are frequently created and released (active iterator count around 250, write OPS around 20K). The logging shows before patching, `AddLiveFiles()` call takes 100+ms and in that process copies 250W file metas with 6W of them being unique.

<p align="center">(left: patched, right: vanilla)</p>
{6CF6D5FB-AF52-4E5D-A8AC-321A8F1D0D18}
{8D5DEF79-B6F3-4CBC-A1F2-5D4F95C33A1A}
{9CA22B47-140B-4971-9C18-FB8F45E4AF79}

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
I want to take a look at the metrics of the number of snapshots

**Comment by tabokie** [comment]
> I want to take a look at the metrics of the number of snapshots

@Connor1996 

http://172.16.5.123:43088/d/RDVQiEzZz/test-tikv-details?orgId=1&from=1624530590279&to=1624533504062

{2779A187-048D-4638-A747-0B9B8FF042CF}

**Comment by zhangjinpeng1987** [comment]
How about push back to rocksdb upstream?

**Comment by yiwu-arbug** [comment]
> How about push back to rocksdb upstream?

Let's do that after code review.

**Comment by yiwu-arbug** [comment]
duplicated with #250

**Pull request closed without merging**
