### PR TITLE
port patch of tikv to 6.25.3

### PR DESCRIPTION
**Pull request by Little-Wallace**

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Looking good overall.

Any changes worth mentioning, aside from copying over the code from 6.4.tikv branch? Asking because it is hard to see if there's any change.

As per encryption and file inspected env, we may consider move to the newer `FileSystem` API. But we are good for now.

**Comment by yiwu-arbug** [comment]
There are some more patches need to migrate:
https://github.com/tikv/rocksdb/commit/96d7d163ab40c6f7122605f3705c4407e12d6fe1
https://github.com/tikv/rocksdb/commit/906258cb21d221162dd9047e2753237d7070fb34
https://github.com/tikv/rocksdb/commit/979a985cfc5de5a600046b19d76c81b0ee39b4bf
https://github.com/tikv/rocksdb/commit/bf9fa0eb8e6fe10ccc4c50a9e87acde4aacb17d2
https://github.com/tikv/rocksdb/commit/953f8b2f23eabdc0df9adb4fc50b566ae0c5a5e9
https://github.com/tikv/rocksdb/commit/7e6c07debf03604750b9b7a3ce4b0e785f3feb02
https://github.com/tikv/rocksdb/commit/0d1ac74cce5397485d8d132cbcd5ba702a578925
https://github.com/tikv/rocksdb/commit/afa47b6e5d5a8c96db3d6213aee8aa6ea12c2b74
https://github.com/tikv/rocksdb/commit/6b97c0567c4694ef1d06374d54bf582e541d215d
https://github.com/tikv/rocksdb/commit/f236fe443d06337ca2538414c62f70ba17b8e409

There might be more. But it is okay to have them in separate PR.

**Review by Connor1996 — COMMENTED** [review]
Can you list all the commits that we patched and make a checkbox list for them to see if any is missing?

**Comment by ethercflow** [comment]
Hi @Little-Wallace Would you please also pick https://github.com/facebook/rocksdb/commit/b0c5ecd6b33398eae73c5d22b37fa820f41c804e? 
We hope we can online config `max_subcompactions` thanks!

**Comment by tabokie** [comment]
Superseded by #277

**Pull request closed without merging**
