### PR TITLE
Reimplement print single sst meta when dump manifest

### PR DESCRIPTION
**Pull request by hunterlxt**
Original PR: https://github.com/facebook/rocksdb/pull/8557

Signed-off-by: Xintao <hunterlxt@live.com>

### CODE REVIEW

**Comment by hunterlxt** [comment]
@Connor1996 comments mentioned in RocksDB PR's are addressed. except this one https://github.com/facebook/rocksdb/pull/6716#discussion_r410289174

**Comment by yiwu-arbug** [comment]
Can we update or re-send the upstream PR?

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
