### PR TITLE
Cherry-pick version builder related changes

### PR DESCRIPTION
**Pull request by tabokie**
Cherry-pick the following commits:
```
* 75e7cb923 Make it possible to look up files by number in VersionStorageInfo (facebook/rocksdb#6862)
* 7861b5a3d Improve consistency checks in VersionBuilder (facebook/rocksdb#6901)
* 37c7c7175 Revisit the handling of the case when a file is re-added to the same level (facebook/rocksdb#6939)
```
Signed-off-by: tabokie <xy.tao@outlook.com>

### CODE REVIEW

**Comment by tabokie** [comment]
Test passed locally.

**Comment by yiwu-arbug** [comment]
What do you plan to use these changes?

**Comment by tabokie** [comment]
> What do you plan to use these changes?

@yiwu-arbug A lot has changed in facebook/rocksdb#8494 since the original PR, and those changes are based on latest `VersionBuilder` code.

**Review by yiwu-arbug — APPROVED** [review]

**Comment by Connor1996** [comment]
> > What do you plan to use these changes?
> 
> @yiwu-arbug A lot has changed in [facebook#8494](https://github.com/facebook/rocksdb/pull/8494) compared to the original PR, and those changes are based on latest `VersionBuilder` code.

But we can still merge the original PR on our side without these changes.

**Comment by tabokie** [comment]
@Connor1996 I fixed several bugs captured by their CI in the upstream PR. And regardless of that purpose, I think cherry-picked commits here are good improvements in safety and quality.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
