### PR TITLE
fix Clang 12 build errors

### PR DESCRIPTION
**Pull request by gregwebs**
I needed these changes to run `make` successfully.

See this issue which points out the problem and has the same patch solution but at a different point in time: https://github.com/facebook/rocksdb/issues/7352

### CODE REVIEW

**Comment by gregwebs** [comment]
The Travis Mac Clang builds failed but it doesn't show any output. Can we retry these jobs? Is there a way to see the output?

**Comment by Connor1996** [comment]
> The Travis Mac Clang builds failed but it doesn't show any output. Can we retry these jobs? Is there a way to see the output?

have triggered the retry of failed jobs

**Comment by gregwebs** [comment]
Still failing with no logs.

**Comment by gregwebs** [comment]
oh, it seems all the PRs are failing on these builds

**Comment by yiwu-arbug** [comment]
The CI is failing for timeout and irrelevant, but looks like they are the only Mac build CI we have.

**Pull request merged**
