### PR TITLE
Upgrade to v7.8.3

### PR DESCRIPTION
**Pull request by cscetbon**
Merge new changes from v7.8.3 :
- Replace ToString by std::to_string as the function was removed
- Fix calls to functions that got their signature updated
- Remove code that was removed between v6.25.1 and v7.8.3 and keep code that was added between v6.25.1 and 6.29.tikv

### CODE REVIEW

**Comment by cscetbon** [comment]
@tabokie I also have a version with a squash merge but I would think that this one would allow you to better see the commits I picked from 7.8.3 and the changes I made on top of it, the diff between v6.25.1. and v6.29.tikv that I used and adapted to the new release.

**Comment by tabokie** [comment]
@cscetbon I have a few questions,

(1) I see you picked the upstream commits from https://github.com/tikv/rocksdb/pull/333/commits/3f763763aaedb78c952d52f2bc58d0b25c6e7105, which is on v7.6.0, but what about upstream changes between 6.29 and 7.6?

Following up on this, the [diff](https://github.com/facebook/rocksdb/compare/6.29.fb...7.8.fb) between 6.29.fb and 7.8.fb contains 925 commits. I think it could be too many to merge manually (because each one of them might conflict with our fork changes). A different approach that I used before is to pick our changes to upstream instead. In https://github.com/tikv/rocksdb/issues/277 I gathered all our changes and cherry-pick them one-by-one. Because our changes are small in quantity, it makes it easier to resolve conflicts and run tests progressively.

(2) And I don't quite follow your comment about diff between v6.25.1 and v6.29, v6.29 should already contains most changes from v6.25 (except for some older bugfixes).

**Comment by cscetbon** [comment]
@tabokie not sure how you've found this but it's not what I did. I actually started from `6.29.tikv` or faad4834 and then applied on top of it all commits starting with 1cecd22de up to v7.8.3 or bf2c335. Why  `1cecd22de ` ? because I figured that its parent e8f116deab was the last commit you took before making your own changes. I then compared the diff between 6.29.tikv and v6.25.1 which I figured was the closest starting point of your changes and compared it to the changes between my resulting branch and v7.8.3 to see if I missed some changes you made but also ensured they were not just cherry-picked PRs that got updated later on.

Let me know if you still think what you said stands here. I see your list is made of 52 patches which is not too big like you said.

**Comment by tabokie** [comment]
> not sure how you've found this but it's not what I did.

Oh, apparently GitHub only shows the most recent commits so I read it wrong.

> I then compared the diff between 6.29.tikv and v6.25.1 which I figured was the closest starting point of your changes

I see. But all our changes are rebased to 6.29.fb, so it's fine to just compare 6.29.tikv and 6.29.fb.

I think this looks good overall, you just need to pass our CI then.

**Review by Connor1996 — COMMENTED** [review]
Maybe push to branch `7.8.tikv` instead of `6.29.tikv`?

**Comment by tabokie** [comment]
> Maybe push to branch `7.8.tikv` instead of `6.29.tikv`?

Yes, this PR is only used to run CI.

**Comment by cscetbon** [comment]
> I think this looks good overall, you just need to pass our CI then

Cool, now I'm gonna need your help to figure out what is missing and why those remaining tests don't pass. I was able to fix most of them but these remaining tests probably require knowledge about the changes you made. Also some of them didn't exist in the past in your branch but porting your changes, probably because I did it wrong or because it requires more changes than it did before, break it and it's hard to figure out why. 

I'll also try on my side to compare the 2 branches you gave me, maybe some changes are still missing ...

**Comment by tabokie** [comment]
> figure out what is missing and why those remaining tests don't pass

You can start by fixing the format and build issues. Other than that, I see there's only one test failing right now (`CreateLoggerFromOptions`), you can disable it first (by renaming the test to "DISABLED_xxx").

**Comment by cscetbon** [comment]
> > figure out what is missing and why those remaining tests don't pass
> 
> You can start by fixing the format and build issues. Other than that, I see there's only one test failing right now (`CreateLoggerFromOptions`), you can disable it first (by renaming the test to "DISABLED_xxx").

It builds with no issue but yeah I need to fix the formatting

**Comment by tabokie** [comment]
> It builds with no issue

There're actually multiple pipelines in "idc-jenkins-ci-rocksdb/test". In "arm test", the test `CreateLoggerFromOptions` failed, in other pipelines, it fails to build.

**Comment by cscetbon** [comment]
@tabokie I think the formatting is fixed using clang 13, waiting for it to be approved to run again and check.

Looking at your Jenkins pipeline https://ci.pingcap.net/blue/organizations/jenkins/rocksdb_ghpr_test/detail/rocksdb_ghpr_test/498/pipeline/ **x86** (debug release) is marked as failed but when I click on it everything is green so there is something fishy.

Moreover those parallel tests that fail don't fail on me on the same compilation error but more on tests, like I said before, when I run those tests on an arm machine in a docker image using zjay437/rocksdb:0.6 image built using https://github.com/cscetbon/rocksdb/tree/merge-v7.8.3/build_tools/ubuntu20_image so it probably comes from the version of gcc that you use. I tried using 8.4.0 and it doesn't fail. What version is your pipeline using ?

**Comment by cscetbon** [comment]
I forgot to add that if you take a look at FB circle's configuration they run tests on ARM only using the current version of gcc which is 9.4.0 and not gcc-8 https://github.com/facebook/rocksdb/blob/v7.8.3/.circleci/config.yml#L851

**Comment by cscetbon** [comment]
@tabokie still waiting to get help from you.

**Comment by tabokie** [comment]
Sorry for the delay, I was oncall and on vacation for the last 3 weeks.. I'll take a look at the CI soon.

**Comment by tabokie** [comment]
> I think the formatting is fixed using clang 13, waiting for it to be approved to run again and check.

Appears to still be failing.

> everything is green so there is something fishy.

I think it's an early abort feature of jenkins to cut down CI runtime.

> so it probably comes from the version of gcc that you use. I tried using 8.4.0 and it doesn't fail. What version is your pipeline using ?

From the log output it is gcc 8.3.1. I presume facebook upstream only requires a minimum version of 7 (based on their INSTALL.md and several CI pipelines that run on 7).

https://github.com/facebook/rocksdb/issues/11225 here is a similar build issue not sure if it helps.

**Comment by cscetbon** [comment]
Except like I said they don't run some tests on earlier versions anymore when you still do and they now fail if you see my previous comments. It suggests that some part of the code are not supposed to be tested under older versions or are no longer compatible.

**Comment by tabokie** [comment]
> Except like I said they don't run some tests on earlier versions anymore when you still do and they now fail if you see my previous comments.

In the same file you are referencing, there's one pipeline that runs tests on gcc-7 (build-linux-gcc-7-with-folly). Plus the build issues we are looking at now is not even related to tests, it's a tool build, which shouldn't be a problem unless the facebook documentation is wrong.

A bit of context here, upgrading our toolchain to newer gcc is doable, but it requires rebuilding base docker image across multiple repositories. I prefer we work on fixing this issue instead.

**Comment by cscetbon** [comment]
Didn't feel I got enough help on this so closing this PR

**Comment by tabokie** [comment]
@cscetbon Next time before you contribute be sure you have the necessary skills required to fix *build issues* in CI. Otherwise it's just a waste of everybody's time. Our team is small and we don't have the bandwidth to serve contributors the way you'd expected.

**Comment by cscetbon** [comment]
Don't put it this way, I had to wait a long time and there are things on your CI that I don't have access to. The person who wasted the most of his time is me. Your comment is just disrespectful.

**Comment by tabokie** [comment]
> I had to wait a long time

How exactly have I kept you waiting though? If you just bother to take a look at our chat history, which is just a few scrolls above, I have responded your comment in the same day 9 out of 10. The only time I didn't respond I have expressed my apology and reason.

> there are things on your CI that I don't have access to.

You never mentioned anything about this. (It's probably be something I can't access as well.) I think this says something about your communication skills.

> Your comment is just disrespectful.

Talking about respect, I think I'm being perfectly respectful. After all, I did point out it is a waste of your time too. And I would hurt to see anyone wasting their time, including yours.

**Comment by cscetbon** [comment]
>>Your comment is just disrespectful.

>Talking about respect, I think I'm being perfectly respectful. After all, I did point out it is a waste of your time too. And I would hurt to see anyone wasting their time, including yours

My comment was related to not having anymore time to spend on it and the fact it took time to get responses here. But I wasn't even blaming you, just giving the reason, knowing that I spent nights on this and the fact it takes years to compile, fix, try etc...
Regarding your previous remark about wasting your time If you don't see any issue it's a you problem. An Open-source project is supported by its users and contributors and you should just thank people for contributing or attempting to do so.

**Comment by tabokie** [comment]
> But I wasn't even blaming you

What can I say, you must have a unique way of communicating. Because I felt strong sense of blaming and making excuses from the get-go. If it's not clear to you, let my give examples:

> It builds with no issue

> like I said before

> Except like I said they don't run some tests on earlier versions anymore when you still do and they now fail if you see my previous comments.

> Didn't feel I got enough help

I don't want to analyze them for you, if you can't see how poorly you communicate "it's a you problem".

From my point of view, I gave clear instruction that CI format and build need to pass before we can make further progress. You don't need to fix any test errors, just mute them and I'll look at them later.

But you did not try to fix any of the build issues (based on the commit you submitted). You repeatedly claim facebook doesn't support our gcc version anymore when evidently they still do (based on the link you gave me). You also repeatedly blame me for not reading your comment carefully (based on the quote I give).

> Regarding your previous remark about wasting your time If you don't see any issue it's a you problem.

Of course I don't see any problem. My time is wasted, period. It's not like we are competing who is wasting more.

> An Open-source project is supported by its users and contributors and you should just thank people for contributing or attempting to do so.

No I am not thankful for you. As I have pointed out clearly before, you must have certain level of skills to contribute. Our project, especially this one, requires a higher level of skill compared to other better funded project, because there's only a handful of people can review PR in this repo, and we all have higher obligations elsewhere.

In the hope that this PR does not waste any one second of my time, or yours, I'm going to lock conversation.

**Pull request closed without merging**
