### PR TITLE
Revert #252 and disable ignore_unknown_options only for lower version

### PR DESCRIPTION
**Pull request by tabokie**
With #252, newer version can't be rolled back anymore. Revert it.
Also only disable ignore_unknown_options for lower version, so that newer releases of TiKV with new config items can be rolled back to this version.

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
temporarily disabling mac build in CI.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
